### ISSUE TITLE
Certbot letsencrypt on different port than 443

### ISSUE THREAD

**Issue by Bergiu** [Undeadhunter/docker-nextcloud-letsencrypt#3]
Is it possible to get this working on different ports than 443?

I have exactly the same problem like this guy:
https://serverfault.com/questions/805666/certbot-letsencrypt-on-different-port-than-443

**Comment by Undeadhunter** [comment]
No, since certbot needs 80/443 to do the verification on. 
https://community.letsencrypt.org/t/support-for-ports-other-than-80-and-443/3419/100

You COULD do the authentication, then change the port in docker. Not sure how this would work out, also auto-renew will fail.

**Comment by Bergiu** [comment]
> This is not possible with certbot. You should take a look at the other implementation method here: https://community.letsencrypt.org/t/list-of-client-implementations/2103

can't I just change the certbot part in the image to an alternative program, that supports this?

or is there any other solution like buying a small server that maps the port 443 to my port?

**Comment by Undeadhunter** [comment]
Yes you can always create a new docker and replace certbot.

What is your issue of being unable to use 443? Might give a better solution
that way

**Comment by Bergiu** [comment]
I am in a subnet and can't forward other ports to my pc

**Comment by Undeadhunter** [comment]
Not much I can help with that.
