### ISSUE TITLE
Nextcloud version is Outdated

### ISSUE THREAD

**Issue by Franconian-IT** [Undeadhunter/docker-nextcloud-letsencrypt#4]
The Nextcloud version included in the Docker container is not on latest patch level anymore.

Please update to Nextcloud version 11.0.3 or to the new major release version 12.0.0.

Thank you so much for the container!

**Comment by tcuc** [comment]
i think it would pull inn the newer version if you built the image yourself. 
if not, the upgrade was easy from the web UI, just log in as the super user.

**Comment by Undeadhunter** [comment]
Forced the docker to build on hub, should be good now.
